/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author Sebas
 */
public class Sedes extends javax.swing.JFrame {

    /**
     * Creates new form Sedes
     */
    public Sedes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labeldato = new javax.swing.JLabel();
        BotonSJ = new javax.swing.JButton();
        BotonCart = new javax.swing.JButton();
        BotonAla = new javax.swing.JButton();
        Botoncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Labeldato.setText("¿Qué sede desea editar?");

        BotonSJ.setText("San José");
        BotonSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSJActionPerformed(evt);
            }
        });

        BotonCart.setText("Cartago");
        BotonCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCartActionPerformed(evt);
            }
        });

        BotonAla.setText("Alajuela");
        BotonAla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlaActionPerformed(evt);
            }
        });

        Botoncancelar.setText("Cancelar");
        Botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Labeldato))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Botoncancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BotonSJ)
                        .addGap(52, 52, 52)
                        .addComponent(BotonCart)
                        .addGap(48, 48, 48)
                        .addComponent(BotonAla)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Labeldato)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSJ)
                    .addComponent(BotonCart)
                    .addComponent(BotonAla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Botoncancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoncancelarActionPerformed
        // TODO add your handling code here:
        
        AdministradorChanges ventana2 = new AdministradorChanges();
        ventana2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotoncancelarActionPerformed

    private void BotonSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSJActionPerformed
        // TODO add your handling code here:
        
        SanJose ventana2 = new SanJose();
        ventana2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotonSJActionPerformed

    private void BotonCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCartActionPerformed
        // TODO add your handling code here:
        
        Cartago ventana2 = new Cartago();
        ventana2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotonCartActionPerformed

    private void BotonAlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlaActionPerformed
        // TODO add your handling code here:
        
        Alajuela ventana2 = new Alajuela();
        ventana2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAlaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAla;
    private javax.swing.JButton BotonCart;
    private javax.swing.JButton BotonSJ;
    private javax.swing.JButton Botoncancelar;
    private javax.swing.JLabel Labeldato;
    // End of variables declaration//GEN-END:variables
}
